config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  draw :api

  devise_for :users, :controllers => { registrations: 'users', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  end
  get '/users/auth/github/callback' => 'omniauth_callbacks#github' # Fix for Github oauth

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#index'
  get '/' => 'home#index', as: :home
  get '/hakkinda' => 'posts#about', as: :about
  get '/kategoriler' => 'categories#index', as: :categories
  get '/kategori/:id' => 'categories#show', as: :category
  get '/galeri' => 'galleries#index', as: :galleries
  get '/galeri/yeni' => 'galleries#new', as: :new_gallery
  post '/galeri/yeni' => 'galleries#create', as: :create_gallery
  get '/galeri/:id/like/(:token)' => 'galleries#like', as: :like_gallery
  get '/galeri/:id/unlike/(:token)' => 'galleries#unlike', as: :unlike_gallery
  get '/galeri/:id' => 'galleries#show', as: :gallery
  get '/ara/:query' => 'searches#show', as: :search
  get '/istatistikler/(:id)/(:post_category_id)' => 'stats#index', as: :stats
  get '/ekipman/:id' => 'products#show', as: :product
  get '/ekipman/:id/vote' => 'products#vote', as: :vote_product
  get '/abone-ol' => 'subscribers#new', as: :new_subscriber
  post '/abone-ol' => 'subscribers#create', as: :create_subscriber
  get '/feed' => 'posts#feed', as: :feed, :format => 'rss'
  get '/profilim' => 'profiles#edit', as: :edit_profile
  get '/profilim/favori-ekipmanlarim' => 'profiles#voted', as: :voted_products
  patch '/profilim' => 'profiles#update', as: :update_profile

  get '/:id/like/(:token)' => 'posts#like', as: :like_post
  get '/:id/unlike/(:token)' => 'posts#unlike', as: :unlike_post
  get '/:id' => 'posts#show', as: :post
end

app/views/shared/_subscribe_form.html.erb
<div class="clearfix"></div>
<section class="subscribe-panel col-md-8 col-md-offset-2">
  <div class="subscribe-form">
    <div class="form-title">Abone ol, röportajları kaçırma!</div>
    <%= form_for Subscriber.new, url: create_subscriber_path, remote: true do |f| %>
      <%= token_tag nil %>
      <%= f.text_field :email, placeholder: 'E-posta Adresiniz' %>
      <%= f.button "KAYIT OL", class: 'btn btn-default' %>
    <% end %>
    <div class="social-buttons">
      <a href="https://facebook.com/calismamasamcom" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="https://twitter.com/calismamasamcom" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.instagram.com/calismamasamcom" target="_blank"><i class="fa fa-instagram"></i></a>
      <a href="https://calismamasam.com/feed?format=rss"><i class="fa fa-rss"></i></a>
      <a href="https://itunes.apple.com/tr/podcast/cal-sma-masam/id1184205170"><i class="fa fa-podcast"></i></a>
    </div>
  </div>
</section>

app/views/shared/_user.html.erb
<% if user_signed_in? %>
  <div class="user-panel">
    <a href="javascript:void(0)" data-toggle="popover">
      <%= image_tag gravatar_url(current_user.email, 64) %>
    </a>
    <div id="popover-content" class="list-group" style="display: none">
      <ul>
        <% if current_user.admin? %>
          <li>
            <%= link_to('Yönetim Paneli', '/admin') %>
          </li>
        <% end %>
        <li>
          <%= link_to('Profil Ayarları', edit_profile_path) %>
        </li>
        <li>
          <%= link_to('Favorilerim', voted_products_path) %>
        </li>
        <li>
          <%= link_to('Galeri Ekle', new_gallery_path) %>
        </li>
        <li>
          <%= link_to('Çıkış Yap', destroy_user_session_path, method: :delete) %>
        </li>
      </ul>
    </div>
  </div>
<% else %>
  <div class="user-panel">
    <a href="javascript:void(0)" data-toggle="popover">
      <%= image_tag gravatar_url("", 64) %>
    </a>
    <div id="popover-content" class="list-group" style="display: none">
      <ul>
        <li>
          <%= link_to('Giriş Yap', new_user_session_path) %>
        </li>
        <li>
          <%= link_to('Kayıt Ol', new_user_registration_path) %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_vote.html.erb
<% if user_signed_in? %>
  <% if product.liked? current_user%>
    <i class="fa fa-heart product-vote"></i>
  <% else %>
    <i class="fa fa-heart-o product-vote"></i>
  <% end %>
<% end %>

app/views/shared/like.js.erb
<% if @like.errors.any? %>
  swal({ type: "error", title: "Hata", text: "Daha önce puan verdiniz.", confirmButtonColor: '#00d888', confirmButtonText: "Tamam" });
<% else %>
  var link = $('.like-panel a');
  link.addClass('active');
  link.attr('href', link.attr('href').replace('like', 'unlike'));
<% end %>
$('.like-panel .likes-count').html('<%= @likes_count %> kişi beğendi');

app/views/shared/unlike.js.erb
var link = $('.like-panel a');
link.removeClass('active');
link.attr('href', link.attr('href').replace('unlike', 'like'));

<% if @likes_count > 0 %>
  $('.like-panel .likes-count').html('<%= @likes_count %> kişi beğendi');
<% else %>
  $('.like-panel .likes-count').html('');
<% end %>