config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  draw :api

  devise_for :users, :controllers => { registrations: 'users', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  end
  get '/users/auth/github/callback' => 'omniauth_callbacks#github' # Fix for Github oauth

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#index'
  get '/' => 'home#index', as: :home
  get '/hakkinda' => 'posts#about', as: :about
  get '/kategoriler' => 'categories#index', as: :categories
  get '/kategori/:id' => 'categories#show', as: :category
  get '/galeri' => 'galleries#index', as: :galleries
  get '/galeri/yeni' => 'galleries#new', as: :new_gallery
  post '/galeri/yeni' => 'galleries#create', as: :create_gallery
  get '/galeri/:id/like/(:token)' => 'galleries#like', as: :like_gallery
  get '/galeri/:id/unlike/(:token)' => 'galleries#unlike', as: :unlike_gallery
  get '/galeri/:id' => 'galleries#show', as: :gallery
  get '/ara/:query' => 'searches#show', as: :search
  get '/istatistikler/(:id)/(:post_category_id)' => 'stats#index', as: :stats
  get '/ekipman/:id' => 'products#show', as: :product
  get '/ekipman/:id/vote' => 'products#vote', as: :vote_product
  get '/abone-ol' => 'subscribers#new', as: :new_subscriber
  post '/abone-ol' => 'subscribers#create', as: :create_subscriber
  get '/feed' => 'posts#feed', as: :feed, :format => 'rss'
  get '/profilim' => 'profiles#edit', as: :edit_profile
  get '/profilim/favori-ekipmanlarim' => 'profiles#voted', as: :voted_products
  patch '/profilim' => 'profiles#update', as: :update_profile

  get '/:id/like/(:token)' => 'posts#like', as: :like_post
  get '/:id/unlike/(:token)' => 'posts#unlike', as: :unlike_post
  get '/:id' => 'posts#show', as: :post
end

app/models/post.rb
class Post < ApplicationRecord
  include Likeable
  include AlgoliaSearch
  extend FriendlyId

  friendly_id :title, use: :slugged

  cache_index :slug, unique: true

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :products
  has_many :post_images

  cache_has_many :post_images, embed: true

  has_attached_file :image,
                    styles: { full: '1500x750#', normal: '500x250#', thumb: '200x200#' },
                    convert_options: {
                      full: '-quality 80 -interlace Plane',
                      normal: '-quality 80 -interlace Plane',
                      thumb: '-quality 80 -interlace Plane'
                    },
                    default_url: '/images/:style/missing.png',
                    s3_headers: {
                      'Cache-Control' => 'max-age=315576000',
                      'Expires' => 10.years.from_now.httpdate
                    },
                    use_timestamp: false

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :body, :title, :job_title, :published_at, presence: true

  scope :active, -> { where(is_active: true).where('published_at < ?', Time.current).order(published_at: :desc, created_at: :desc) }
  scope :notifiable, -> { where(is_active: true).where('published_at between ? and ? and notified_at is null', 5.minutes.ago, Time.current + 5.minutes).order(published_at: :desc, created_at: :desc) }

  before_save :generate_file_name, if: :image_file_name_changed?

  algoliasearch per_environment: true do
    attribute :is_active, :title, :job_title, :company, :body, :slug
    add_attribute :published_at do
      published_at.present? ? published_at.to_i : (Time.current + 10.years).to_i
    end
    add_attribute :categories do
      categories.map(&:title)
    end
    add_attribute :products do
      products.map(&:name_with_brand)
    end
    tags do
      tags = []
      tags << 'published' if decorate.active?
      tags
    end

    customRanking ['desc(published_at)']
    attributesForFaceting %i[company categories products]
    minWordSizefor1Typo 8
    minWordSizefor2Typos 10
    hitsPerPage 20
  end

  private

  def generate_file_name
    extension = File.extname(image_file_name).downcase
    random = Random.new.rand(10..1000)
    file_name = if image.exists?
                  "#{title.parameterize}-#{job_title.parameterize}-#{random}"
                else
                  "#{title.parameterize}-#{job_title.parameterize}"
                end
    image.instance_write(:file_name, "#{file_name}#{extension}")
  end
end

app/controllers/api/v1/posts_controller.rb
# coding: utf-8
class Api::V1::PostsController < ApplicationController
  def index
    @posts = Post.active
    render json: @posts
  end

  def show
    @post = Post.friendly.find(params[:id])
    render json: @post, serializer: PostSerializer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show like unlike]
  before_action :find_user, only: %i[like unlike]

  def show; end

  def like
    @like = @user.like(Post, @post.id)
    @likes_count = @post.likes_count
    @post.touch

    respond_to do |format|
      format.html { redirect_to(post_path(@post)) }
      format.js  { render 'shared/like' }
    end
  end

  def unlike
    @unlike = @user.unlike(Post, @post.id)
    @likes_count = @post.likes_count
    @post.touch

    respond_to do |format|
      format.html { redirect_to(post_path(@post)) }
      format.js  { render 'shared/unlike' }
    end
  end

  def about; end

  def feed
    @posts = Post.active
    respond_to do |format|
      format.rss { render layout: false }
    end
  end

  private

  def find_post
    @post = Post.fetch_by_slug(params[:id])
    return redirect_to root_path unless @post.present?
    @post = @post.decorate
    redirect_to root_path unless @post.active?
  end

  def find_user
    (@user = User.fetch_by_token(params[:token])) || raise('not found')
    redirect_to new_user_session_path unless @user.present?
  end
end

app/views/posts/_post.html.erb
<% row_class = "col-md-10 col-md-offset-1" if size == :big %>
<% row_class = "col-md-8 col-md-offset-2" if size == :normal %>

<% cache ["post", post.id, post.updated_at] do %>
  <% job_and_company = post.company.present? ? "#{post.job_title} @ #{post.company}" : post.job_title %>
  <article class="post <%= row_class %>">
    <figure>
      <a href="<%= post_path(post.slug) %>" onclick="ga('send', 'event', 'post-links', '<%= post.title %>');">
        <%= image_tag(post.image(:normal), data: {src: post.image(:full)}, class: 'post-image lazyload blur-up', alt: post.title, title: post.title) %>
      </a>
    </figure>
    <div class="post-info center">
      <h2>
        <a href="<%= post_path(post.slug) %>" onclick="ga('send', 'event', 'post-links', '<%= post.title %>');">
          <%= post.title %>
        </a>
      </h2>
      <span class="post-title"><%= job_and_company %></span>
      <div class="row hidden-xs">
        <div class="col-sm-10 col-sm-offset-1">
          <p class="post-description"><%= post.description %></p>
        </div>
      </div>
    </div>
  </article>
<% end %>

app/views/posts/_small_post.html.erb
<% row_class = "col-xs-6 dual-post" if dual == true %>
<% row_class = "col-md-3 col-xs-6" if dual == false %>

<% cache ["small-post", post.id, post.updated_at, row_class] do %>
  <% job_and_company = post.company.present? ? "#{post.job_title} @ #{post.company}" : post.job_title %>
  <article class="post small-post <%= row_class %>">
    <figure>
      <a href="<%= post_path(post.slug) %>" onclick="ga('send', 'event', 'post-links', '<%= post.title %>');">
        <%= image_tag(post.image(:normal), data: {src: post.image(:full)}, class: 'post-image lazyload blur-up', alt: post.title, title: post.title) %>
      </a>
    </figure>
    <div class="post-info">
      <h3>
        <a href="<%= post_path(post.slug) %>" onclick="ga('send', 'event', 'post-links', '<%= post.title %>');">
          <%= post.title %>
        </a>
      </h3>
      <span class="post-title"><%= job_and_company %></span>
      <p class="post-description hidden-xs"><%= truncate post.description, length: 120 %></p>
    </div>
  </article>
<% end %>

app/views/posts/_social_buttons.html.erb
<div class="social-buttons">
  <div class="social-buttons-title">Paylaş</div>
  <ul>
    <li>
      <a onClick="window.open('http://www.facebook.com/sharer.php?s=100&p[title]=<%= @post.title %>&p[url]=<%= url_for(:only_path => false) %>&p[images][0]=<%= @post.image(:full) %>','sharer','toolbar=0,status=0,width=580,height=325');ga('send', 'event', 'social-share-buttons', 'facebook', '<%= @post.title %>');" href="javascript: void(0);">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a onClick="window.open('https://twitter.com/intent/tweet?url=<%= url_for(:only_path => false) %>&text=<%= @post.title %> - <%= @post.job_title %>%0A&via=calismamasamcom','sharer','toolbar=0,status=0,width=600,height=500');ga('send', 'event', 'social-share-buttons', 'twitter', '<%= @post.title %>');" href="javascript: void(0);">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a onClick="window.open('https://telegram.me/share/url?url=<%= url_for(:only_path => false) %>','sharer','toolbar=0,status=0,width=600,height=500');ga('send', 'event', 'social-share-buttons', 'telegram', '<%= @post.title %>');" href="javascript: void(0);">
        <i class="fa fa-telegram"></i>
      </a>
    </li>
  </ul>
  <div class="clear"></div>
</div>

app/views/posts/_stats.html.erb
<% if @post.products.any? %>
  <div class="table-responsive stats-table">
    <h2>Kullandığı Ekipmanlar</h2>
    <table class="table products-table">
      <thead>
        <tr>
          <td width="50%">Donanım</td>
          <td width="50%">Yazılım</td>
        </tr>
      </thead>
      <tbody>
        <td width="50%">
          <table>
            <tbody>
              <% @post.products.where(category_id: ProductCategory.find_by(title: 'Donanım')&.subtree_ids).each do |product| %>
                <tr>
                  <td width="20">
                    <%= render "posts/vote", product: product %>
                  </td>
                  <td width="45">
                    <%= link_to product_path(product) do %>
                      <%= image_tag(product.image(:thumb), width: '30', alt: product.decorate.name_with_brand, title: product.decorate.name_with_brand) %>
                    <% end %>
                  </td>
                  <td>
                    <div class="product-title">
                      <%= link_to product.decorate.name_with_brand, product_path(product) %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </td>
        <td width="50%">
          <table>
            <tbody>
              <% @post.products.where(category_id: ProductCategory.find_by(title: 'Yazılım')&.subtree_ids).each do |product| %>
                <tr>
                  <td width="20">
                    <%= render "posts/vote", product: product %>
                  </td>
                  <td width="45">
                    <%= link_to product_path(product) do %>
                      <%= image_tag(product.image(:thumb), width: '30', alt: product.decorate.name_with_brand, title: product.decorate.name_with_brand) %>
                    <% end %>
                  </td>
                  <td>
                    <div class="product-title">
                      <%= link_to product.decorate.name_with_brand, product_path(product) %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </td>
      </tbody>
    </table>
  </div>
<% end %>

app/views/posts/_vote.html.erb
<% if user_signed_in? %>
  <% if product.liked? current_user%>
    <i class="fa fa-heart product-vote active"></i>
  <% else %>
    <i class="fa fa-heart-o product-vote"></i>
  <% end %>
<% end %>

app/views/posts/about.html.erb
<div class="row post-page">
  <article class="post col-md-8 col-md-offset-2">
    <div class="post-body">
      <h1>
        Çalışma Masam Nedir?
      </h1>
      <p>
        Çalışma Masam, teknoloji ile iç içe olan, sektöründeki yenilikleri takip eden ve aynı zamanda bunları paylaşmaktan keyif alan profesyonellerin; kullandığı cihazlar ve yazılımları, dinlediği müzikleri ve diğer merak edilen soruları cevapladığı bir röportaj sitesidir. 2016 Kasım ayından bugüne toplamda <b><%= Post.active.count %></b> kişiyle röportaj yayınlanmıştır.
      </p>
      <h1 style="margin-top: 80px;">Sorular</h1>

      <h2 style="margin-top: 50px;">Röportaj için kişi önerebilir miyim?</h2>
      <p>Formata uygun olduğunu düşündüğünüz kişileri <a href="mailto:info@calismamasam.com">info@calismamasam.com</a> adresine e-mail göndererek önerebilirsiniz. Kişi hakkında bilgi sahibi olabilmemiz için sosyal medya hesaplarını da ekleyebilirsiniz.</p>

      <h2 style="margin-top: 50px;">Röportaj için kendimi önerebilir miyim?</h2>
      <p>Tabii ki, sizin hakkınızda daha fazla bilgi sahibi olabilmemiz için sosyal medya hesaplarınızı da ekleyerek <a href="mailto:info@calismamasam.com">info@calismamasam.com</a> adresine e-mail gönderebilirsiniz.</p>

      <h2 style="margin-top: 50px;">Çalışma Masam'ı kim yönetiyor?</h2>
      <p>Merhaba, ben <a href="https://twitter.com/tgezginis">Tolga Gezginiş</a>. Öneri ve görüşleriniz için benimle <a href="https://twitter.com/tgezginis">Twitter</a> adresim üzerinden iletişime geçebilirsiniz.</p>

      <h2 style="margin-top: 50px;">Nasıl katkıda bulunabilirim?</h2>
      <p>Sosyal medya üzerinde yapacağınız paylaşımlarla bize destek olabilir, daha fazla kişiye ulaşmamızı sağlayabilirsiniz.</p>
    </div>
  </article>

  <%= render 'shared/subscribe_form' %>
</div>

app/views/posts/show.amp.erb
<%= content_for :html_title, @post.title %>
<%= content_for :html_description, @post.description unless @post.description.nil? || @post.description == '' %>
<%= content_for :html_twitter_description, @post.job_and_company %>
<%= content_for :html_meta_image, @post.image(:full) %>
<%= content_for :html_meta_post_published_time, @post.published_at, format: :short %>

<% cache ["post", @post.id, @post.updated_at, @post.categories, @post.fetch_post_images, current_user&.id, @post.products] do %>
  <div class="row post-page">
    <article class="post col-md-10 col-md-offset-1 container">
      <%= image_tag(@post.image(:normal), data: {src: @post.image(:full)}, class: 'post-image lazyload blur-up', alt: @post.title, title: @post.title, layout: 'responsive') %>

      <h1><%= @post.title %></h1>
      <h2 class="post-job"><%= @post.job_and_company %></h2>

      <div class="clearfix"></div>
      <div class="post-body">
        <% body = @post.body.split("## Hangi yazılımları kullanıyorsun?") %>
        <%= markdown body[0] %>

        <% if @post.fetch_post_images.any? %>
          <amp-carousel layout="responsive"
            height="300"
            width="500"
            type="slides">
            <% @post.fetch_post_images.each do |image| %>
              <%= image_tag image.image(:full) %>
            <% end %>
          </amp-carousel>
        <% end %>

        <%= markdown ["## Hangi yazılımları kullanıyorsun?", body[1]].join %>
      </div>
    </article>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= content_for :html_title, @post.title %>
<%= content_for :html_description, @post.description unless @post.description.nil? || @post.description == '' %>
<%= content_for :html_twitter_description, @post.job_and_company %>
<%= content_for :html_meta_image, @post.image(:full) %>
<%= content_for :html_meta_post_published_time, @post.published_at, format: :short %>
<% @liked = current_user.present? ? @post.liked?(current_user) : false %>

<% cache ["post", @post.id, @post.updated_at, @post.categories, @post.fetch_post_images, current_user&.id, @post.products, @liked] do %>
  <div class="row post-page">
    <article class="post col-md-10 col-md-offset-1 container">
      <h1><%= @post.title %></h1>
      <h2 class="post-job"><%= @post.job_and_company %></h2>
      <p class="post-date"><%= l @post.published_at, format: :short %></p>

      <figure>
        <%= image_tag(@post.image(:normal), data: {src: @post.image(:full)}, class: 'post-image lazyload blur-up', alt: @post.title, title: @post.title) %>
      </figure>

      <div>
        <div class="pull-right twitter-panel">
          <% unless @post.twitter_url.nil? || @post.twitter_url == '' %>
            <%= link_to @post.twitter_url, target: '_blank', onclick: "ga('send', 'event', 'post-page-links', 'twitter-url', '#{@post.twitter_url.gsub("https://twitter.com/", "")}');" do %>
              <span class="post-twitter">
                <i class="fa fa-twitter"></i>
              </span>
            <% end %>
          <% end %>
        </div>
        <div class="pull-left like-panel">
          <div>
            <% if current_user.present? %>
              <% if @liked %>
                <%= link_to unlike_post_path(@post, token: current_user.token), remote: true, class: 'active' do %>
                  <i class="fa fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to like_post_path(@post, token: current_user.token), remote: true do %>
                  <i class="fa fa-heart"></i>
                <% end %>
              <% end %>
            <% else %>
              <a href="javascript:likeLogin();"><i class="fa fa-heart"></i></a>
            <% end %>
          </div>
          <div class="likes-count">
            <% if @post.likes_count > 0 %>
              <%= @post.likes_count %> kişi beğendi
            <% end %>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="post-body">
        <% body = @post.body.split("## Hangi yazılımları kullanıyorsun?") %>
        <%= markdown body[0] %>

        <% if @post.fetch_post_images.count > 0 %>
          <div class="images-panel">
            <% if @post.fetch_post_images.any? %>
              <div class="slider">
                <% @post.fetch_post_images.each do |image| %>
                  <div>
                    <a href="<%= image.image(:original) %>" target="_blank">
                      <%= image_tag image.image(:full), class: 'post-inline-image', alt: @post.title, title: @post.title %>
                    </a>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>

        <%= markdown ["## Hangi yazılımları kullanıyorsun?", body[1]].join %>

        <% unless @post.video_url.nil? || @post.video_url == '' %>
          <div class="video-panel">
            <div class="video-title">Ek olarak Doğukan Güven Nomak'ın düzenlediği <a href="https://www.youtube.com/playlist?list=PLAttZmBpvaDwb4gGpLlLiiNh0h_A91Kvp" target="_blank" onclick="ga('send', 'event', 'post-page-links', 'gelistirici-sohbetleri-url', '<%= @post.title %>'">Geliştirici ve Tasarımcı Sohbetleri</a> röportajını da izleyebilirsiniz;</div>
            <%= VideoPlayer::player(@post.video_url, "800", "450", false).html_safe %>
          </div>
        <% end %>
      </div>

      <%= render 'stats' %>
      <%= render 'social_buttons' %>
    </article>

    <%= render 'shared/subscribe_form' %>

    <div id="disqus_thread" class="col-md-8 col-md-offset-2"></div>
    <script>
      (function() {
        var d = document, s = d.createElement('script');
        s.src = '//calismamasam.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>

  <script type="text/javascript">
    $('.product-vote').click(function (e) {
      var parent = $(this).parent().parent();
      var voteUrl = parent.find('a').attr('href') + '/vote';
      $.get(voteUrl, function (data) {
        if(data.status)
          parent.find('i').removeClass('fa-heart-o').addClass('fa-heart active');
        else
          parent.find('i').removeClass('fa-heart active').addClass('fa-heart-o');
      });
    });
  </script>
<% end %>