config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  draw :api

  devise_for :users, :controllers => { registrations: 'users', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  end
  get '/users/auth/github/callback' => 'omniauth_callbacks#github' # Fix for Github oauth

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#index'
  get '/' => 'home#index', as: :home
  get '/hakkinda' => 'posts#about', as: :about
  get '/kategoriler' => 'categories#index', as: :categories
  get '/kategori/:id' => 'categories#show', as: :category
  get '/galeri' => 'galleries#index', as: :galleries
  get '/galeri/yeni' => 'galleries#new', as: :new_gallery
  post '/galeri/yeni' => 'galleries#create', as: :create_gallery
  get '/galeri/:id/like/(:token)' => 'galleries#like', as: :like_gallery
  get '/galeri/:id/unlike/(:token)' => 'galleries#unlike', as: :unlike_gallery
  get '/galeri/:id' => 'galleries#show', as: :gallery
  get '/ara/:query' => 'searches#show', as: :search
  get '/istatistikler/(:id)/(:post_category_id)' => 'stats#index', as: :stats
  get '/ekipman/:id' => 'products#show', as: :product
  get '/ekipman/:id/vote' => 'products#vote', as: :vote_product
  get '/abone-ol' => 'subscribers#new', as: :new_subscriber
  post '/abone-ol' => 'subscribers#create', as: :create_subscriber
  get '/feed' => 'posts#feed', as: :feed, :format => 'rss'
  get '/profilim' => 'profiles#edit', as: :edit_profile
  get '/profilim/favori-ekipmanlarim' => 'profiles#voted', as: :voted_products
  patch '/profilim' => 'profiles#update', as: :update_profile

  get '/:id/like/(:token)' => 'posts#like', as: :like_post
  get '/:id/unlike/(:token)' => 'posts#unlike', as: :unlike_post
  get '/:id' => 'posts#show', as: :post
end

app/models/product.rb
class Product < ApplicationRecord
  include Likeable

  extend FriendlyId
  friendly_id :name_with_brand, use: :slugged

  cache_index :slug, unique: true

  belongs_to :category, class_name: 'ProductCategory', foreign_key: 'category_id', counter_cache: true
  belongs_to :brand, class_name: 'ProductBrand', foreign_key: 'brand_id'
  has_and_belongs_to_many :posts

  validates :name, :category_id, presence: true
  validates :name, uniqueness: true

  has_attached_file :image,
                    styles: { full: '1500x1500>', thumb: '200x200#' },
                    convert_options: {
                      full: '-quality 80 -interlace Plane',
                      thumb: '-quality 80 -interlace Plane'
                    },
                    default_url: '/product-images/:style/missing.png',
                    s3_headers: { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate },
                    use_timestamp: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  before_save :generate_file_name, if: :image_file_name_changed?

  def name_with_brand
    decorate.name_with_brand
  end

  private

  def generate_file_name
    extension = File.extname(image_file_name).downcase
    random = Random.new.rand(10..1000)
    file_name = "#{name.parameterize}-#{random}"
    image.instance_write(:file_name, "#{file_name}#{extension}")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:vote]
  before_action :find_product, only: [:show, :vote]

  def show
    @posts = @product.posts.active

    cache_key = ['product-stats-data-result', @product&.id, Post.active.maximum(:updated_at), Product.maximum(:updated_at)]
    result = Rails.cache.fetch(cache_key) do
      StatsInteractors::GetProductChartData.call(product: @product)
    end

    @chart_data = result.chart_data if result.success?
  end

  def vote
    if !@product.liked? current_user
      current_user.like(Product, @product.id)
    elsif @product.liked? current_user
      current_user.unlike(Product, @product.id)
    end
    @product.touch

    respond_to do |format|
      format.json { render json: { :status => @product.liked?(current_user) } }
    end
  end

  private

  def find_product
    @product = Product.fetch_by_slug(params[:id])
    return redirect_to root_path unless @product.present?
    @product = @product.decorate
  end
end

app/views/products/_breadcrumb.html.erb
<ol class="breadcrumb">
  <% @product.category.path.each do |category| %>
    <li><%= link_to category.title, stats_path(id: category.slug) %></li>
  <% end %>
  <li class="active"><%= @product.name_with_brand %></li>
</ol>

app/views/products/_chart.html.erb
<% if @chart_data && @chart_data.any? %>
  <div class="row">
    <%= pie_chart @chart_data, content_for: :charts_js %>
  </div>
<% end %>

app/views/products/_posts.html.erb
<% if @posts && @posts.any? %>
  <div class="table-responsive posts-table">
    <h2>Kullanıcılar</h2>
    <table class="table">
      <tbody>
        <% @posts.each do |post| %>
          <% post = post.decorate %>
          <tr>
            <td width="50">
              <%= link_to post_path(post) do %>
                <%= image_tag(post.image(:thumb), width: '50', alt: post.title, title: post.title) %>
              <% end %>
            </td>
            <td>
              <div class="post-title"><%= link_to post.title, post_path(post) %></div>
              <div class="post-job-title"><%= post.job_and_company %></div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/products/_vote.html.erb
<% if user_signed_in? %>
  <div class="product-vote-panel">
    <% if @product.liked? current_user%>
      <i class="fa fa-heart product-vote active"></i>
      <span class="product-vote">Favorilerimden çıkar</span>
    <% else %>
      <i class="fa fa-heart-o product-vote"></i>
      <span class="product-vote">Favorilerime ekle</span>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  $('.product-vote').click(function (e) {
    var voteUrl = '<%= product_path(@product) %>/vote';
    $.get(voteUrl, function (data) {
      if(data.status) {
        $('i.product-vote').removeClass('fa-heart-o').addClass('fa-heart active');
        $('span.product-vote').html('Favorilerimden çıkar');
      }
      else {
        $('i.product-vote').removeClass('fa-heart active').addClass('fa-heart-o');
        $('span.product-vote').html('Favorilerime ekle');
      }
    });
  });
</script>

app/views/products/show.html.erb
<%= content_for :html_title, @product.name_with_brand %>

<div class="row product-page">
  <article class="col-sm-10 col-sm-offset-1">
    <h1><%= @product.name_with_brand %></h1>
    <%= render 'breadcrumb' %>
    <div class="row">
      <div class="col-md-3">
        <div class="product-image">
          <%= image_tag @product.image(:full) %>
        </div>
        <%= render 'vote' %>
      </div>
      <div class="col-md-9">
        <%= render 'chart' %>
        <%= render 'posts' %>
      </div>
    </div>
  </article>
</div>