config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  draw :api

  devise_for :users, :controllers => { registrations: 'users', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  end
  get '/users/auth/github/callback' => 'omniauth_callbacks#github' # Fix for Github oauth

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'home#index'
  get '/' => 'home#index', as: :home
  get '/hakkinda' => 'posts#about', as: :about
  get '/kategoriler' => 'categories#index', as: :categories
  get '/kategori/:id' => 'categories#show', as: :category
  get '/galeri' => 'galleries#index', as: :galleries
  get '/galeri/yeni' => 'galleries#new', as: :new_gallery
  post '/galeri/yeni' => 'galleries#create', as: :create_gallery
  get '/galeri/:id/like/(:token)' => 'galleries#like', as: :like_gallery
  get '/galeri/:id/unlike/(:token)' => 'galleries#unlike', as: :unlike_gallery
  get '/galeri/:id' => 'galleries#show', as: :gallery
  get '/ara/:query' => 'searches#show', as: :search
  get '/istatistikler/(:id)/(:post_category_id)' => 'stats#index', as: :stats
  get '/ekipman/:id' => 'products#show', as: :product
  get '/ekipman/:id/vote' => 'products#vote', as: :vote_product
  get '/abone-ol' => 'subscribers#new', as: :new_subscriber
  post '/abone-ol' => 'subscribers#create', as: :create_subscriber
  get '/feed' => 'posts#feed', as: :feed, :format => 'rss'
  get '/profilim' => 'profiles#edit', as: :edit_profile
  get '/profilim/favori-ekipmanlarim' => 'profiles#voted', as: :voted_products
  patch '/profilim' => 'profiles#update', as: :update_profile

  get '/:id/like/(:token)' => 'posts#like', as: :like_post
  get '/:id/unlike/(:token)' => 'posts#unlike', as: :unlike_post
  get '/:id' => 'posts#show', as: :post
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% title = !(html_title = yield :html_title).blank? ? "#{html_title} - #{Settings.title}" : Settings.title %>
  <% description = !(html_description = yield :html_description).blank? ? html_description : Settings.description %>
  <% twitter_description = !(html_twitter_description = yield :html_twitter_description).blank? ? html_twitter_description : description %>
  <% keywords = !(html_keywords = yield :html_keywords).blank? ? html_keywords : Settings.keywords %>
  <% meta_image = !(html_meta_image = yield :html_meta_image).blank? ? html_meta_image : "https://calismamasam.com/logo-centered.png" %>
  <% meta_post_published_time = !(html_meta_post_published_time = yield :html_meta_post_published_time).blank? ? html_meta_post_published_time : nil %>

  <title><%= title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="description" content="<%= description %>">
  <meta name="author" content="Tolga Gezginiş">
  <meta name="keywords" content="<%= !(html_keywords = yield :html_keywords).blank? ? html_keywords : Settings.keywords %>">

  <% if meta_post_published_time %>
  <meta property="article:published_time" content="<%= meta_post_published_time %>" />
  <% end %>

  <meta property="og:locale" content="tr_TR" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="<%= title %>" />
  <meta property="og:description" content="<%= description %>" />
  <meta property="og:url" content="<%= url_for(:only_path => false) %>" />
  <meta property="og:site_name" content="Çalışma Masam" />
  <meta property="og:image" content="<%= meta_image %>" />

  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:title" content="<%= title %>"/>
  <meta name="twitter:description" content="<%= twitter_description %>"/>
  <meta name="twitter:site" content="@calismamasamcom"/>
  <meta name="twitter:image" content="<%= meta_image %>"/>
  <meta name="twitter:creator" content="@tgezginis"/>

  <link rel="alternate" type="application/rss+xml" title="Çalışma Masam RSS Feed" href="https://calismamasam.com/feed?format=rss">

  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
  <link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />
  <meta name="application-name" content="&nbsp;"/>
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
  <meta name="msapplication-square70x70logo" content="/mstile-70x70.png" />
  <meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />
  <meta name="msapplication-wide310x150logo" content="/mstile-310x150.png" />
  <meta name="msapplication-square310x310logo" content="/mstile-310x310.png" />
  <meta name="theme-color" content="#ffffff">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<%= ENV['GTM_ID'] %>');</script>
  <!-- End Google Tag Manager -->

  <%= csrf_meta_tags %>
  
  <%= rails_amp_amphtml_link_tag %>
</head>
<body>
  <%= render partial: 'shared/user' %>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Menü</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag('logo.svg', title: Settings.description, alt: Settings.description), root_path, id: 'logo-button', class: 'visible-xs' %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="search-bar">
          <div class="container">
            <div class="col-md-6 col-md-offset-3 col-xs-12">
              <input id="search-input" type="text" value="<%= params[:q] %>" placeholder="aramak istediğiniz ismi yazın">
            </div>
            <i class="cancel-button fa fa-close"></i>
          </div>
        </div>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "röportajlar", "/" %>
          </li>
          <li>
            <%= nav_link_to "kategoriler", categories_path %>
          </li>
          <li class="hidden-xs">
            <%= link_to image_tag('logo.svg', title: Settings.description, alt: Settings.description), root_path, id: 'logo-button', class: 'hidden-xs' %>
          </li>
          <li>
            <%= nav_link_to "galeri", galleries_path %>
          </li>
          <li>
            <%= nav_link_to "istatistikler", stats_path %>
          </li>
          <li class="search-button">
            <span class="hidden-xs"><i class="fa fa-search" onclick="ga('send', 'event', 'header-navigation', 'Arama');"></i></span>
            <span class="visible-xs">arama</span>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <section id="main-container" class="container">
    <%= yield %>
  </section>
  <footer>
    <div>
      <ul>
        <li>
          <%= link_to "röportajlar", "/" %>
        </li>
        <li>
          <%= nav_link_to "kategoriler", categories_path %>
        </li>
        <li>
          <%= nav_link_to "galeri", galleries_path %>
        </li>
        <li>
          <%= nav_link_to "istatistikler", stats_path %>
        </li>
        <li>
          <%= nav_link_to "hakkında", about_path %>
        </li>
      </ul>
      <div class="github-link">
        <a class="github-button" href="https://github.com/calismamasam/calismamasam.com" data-show-count="true" aria-label="Star calismamasam/calismamasam.com on GitHub">Star</a>
      </div>
    </div>
  </footer>
  <%= yield :charts_js %>

  <script async defer src="https://buttons.github.io/buttons.js"></script>

  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= ENV['GTM_ID'] %>"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
</body>
</html>

app/views/layouts/rails_amp_application.amp.erb
<!doctype html>
<html amp>
  <head>
    <% title = !(html_title = yield :html_title).blank? ? "#{html_title} - #{Settings.title}" : Settings.title %>
    <% description = !(html_description = yield :html_description).blank? ? html_description : Settings.description %>
    <% twitter_description = !(html_twitter_description = yield :html_twitter_description).blank? ? html_twitter_description : description %>
    <% keywords = !(html_keywords = yield :html_keywords).blank? ? html_keywords : Settings.keywords %>
    <% meta_image = !(html_meta_image = yield :html_meta_image).blank? ? html_meta_image : "https://calismamasam.com/logo-centered.png" %>
    <% meta_post_published_time = !(html_meta_post_published_time = yield :html_meta_post_published_time).blank? ? html_meta_post_published_time : nil %>

    <meta charset="utf-8">
    <title><%= title %></title>
    <link rel="canonical" href="<%= rails_amp_canonical_url %>" />
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

    <!-- Set page data type by JSON-LD with schema.org. -->
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "*****",
        "mainEntityOfPage": "*****",
        "datePublished": "<%= meta_post_published_time %>"
      }
    </script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora|Open+Sans|Josefin+Sans:300,400,700&subset=latin-ext">

    <!-- Write custom css sytle for amp html here. -->
    <style amp-custom>
      body {
        display: block;
        background: #fff;
        overflow-x: hidden;
        font-family: "Open Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size: 1em;
        line-height: 1.5;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        webkit-tap-highlight-color: #f50057;
        color: #37474F;
        padding: 15px;
      }
      h1 {
        font-size: 24px;
        font-family: 'Josefin Sans';
        color: #37474F;
        margin: 10px 0 0px;
      }
      h2.post-job {
        margin: 0px 0 30px;
        font-size: 14px;
      }
      h2 {
        font-weight: 600;
        font-size: 26px;
        line-height: 1.3;
        margin: 40px 0 10px;
        font-family: 'Josefin Sans';
      }
      amp-img {
      }
      p {
        font-size: 18px;
        line-height: 32px;
        font-weight: 300;
        margin-bottom: 20px;
        font-family: 'Lora',serif;
      }

      .logo {
        margin: 0 50px 20px;
      }

      div.post-body a {
        font-weight: 700;
        color: #f50057;
        /* border-bottom: solid 2px #f50057; */
        font-family: josefin sans;
      }
    </style>

    <%= rails_amp_google_analytics_head %>
    <%= rails_amp_html_header %>
    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
  </head>
  <body>
    <%= rails_amp_google_analytics_page_tracking %>
    <%= link_to image_tag('logo.svg', title: Settings.description, alt: Settings.description, layout: 'responsive', class: 'logo'), root_path %>
    <%= yield %>
  </body>
</html>